export const END_POINT = {

    EXTERNAL_DASHBOARD:{
        END_POINTS:{
            INSPECTION:"",
            GRAPH:""
        },
        POST:1
    },

    GOOGLE_API:{
        API_KEY:""
    },

    CLOUDNARY:{
        API_KEY:"",
        API_SECRET: "",
        CLOUD_NAME:""
    },

    ADD_FLOOR_PLANS:{
        END_POINT:"",
        POST:1
    },
    ADD_REPORT_IMAGE:{
        END_POINT:"",
        POST:1
    },
    Login:{
        END_POINT:"",
        POST:1
    },
    UPDATE_REPORT_STATUS:{
        END_POINT:"",
        POST:1
    },
    RECOVER_PASSWORD:{
        END_POINT:"",
        POST:1
    },
    DASHBOARD:{
        END_POINT:"",
        POST:1
    },
    DASHBOARD_GRAPH:{
        END_POINT:"",
        POST:1
    },
    EXT_DASHBOARD_GRAPH:{
        END_POINT:"",
        POST:1
    },
    INSPECTION_JOBS:{
        END_POINT:"",
        POST:1
    },
    INSPECTION_JOB_DETAIL:{
        END_POINT:"",
        POST:1
    },
    INDIVIDUAL_DROPDOWN:{
        END_POINT:"",
        POST:1
    },
    INSPECTION_DROPDOWN:{
        END_POINT:"",
        POST:1
    },
    INSPECTION_JOB_CREATE_UPDATE:{
        END_POINT:"",
        POST:1
    },
    CLIENTS_LIST:{
        END_POINT:"",
        POST:1
    },
    CLIENT_DETAIL_BY_ID:{
        END_POINT:"",
        POST:1
    },
    CLIENT_DEP_DROPDOWN:{
        END_POINT:"",
        POST:1
    },
    CLIENT_ADD_UPDATE:{
        END_POINT:"",
        POST:1
    },
    GET_NEIGHBORHOOD:{
        END_POINT:"",
        POST:1
    },
    GET_TAGLIST:{
        END_POINT:"",
        POST:1
    },
    GET_BUILDERS:{
        END_POINT:"",
        POST:1
    },
    GET_DISCLOSURE:{
        END_POINT:"",
        POST:1
    },
    GET_GENERIC_RESPONSES:{
        END_POINT:"",
        POST:1
    },
    GET_SECTIONROOM:{
        END_POINT:"",
        POST:1
    },
    GET_ROOMITEM:{
        END_POINT:"",
        POST:1
    },
    LISTDATA:{
        END_POINT:"",
        MODULES:{
            NEIGHBORHOOD:"neighborhood",
            BUILDERS:"builder",
            TAGS:"tag",
            DISCLOSURE:"disclosure",
            GENERIC:'generic',
            SECTION_ROOMS:"sectionRoom",
            ROOM_ITEMS:"roomItem",
            SECTIONS:"section",
            USERS:"user",
            CLIENTS:"client"
        },
        POST:1
    },
    DELETE_LISTDATA:{
        END_POINT:"",
        MODULES:{
            NEIGHBORHOOD:"neighborhood",
            BUILDERS:"builder",
            TAGS:"tag",
            DISCLOSURE:"disclosure",
            GENERIC:'generic',
            SECTION_ROOMS:"sectionRoom",
            ROOM_ITEMS:"roomItem",
            SECTIONS:"section",
            USERS:"user"
        },
        POST:1
    },

    CREATE_UPDATE_LISTDATA:{
        END_POINTS:{
            NEIGHBORHOOD:"createOrUpdateNeighborhood.json",
            BUILDER:"createOrUpdateBuilder.json",
            TAGS:"createOrUpdateTag.json",
            DISCLOSURE:"createOrUpdateADisclosure.json",
            GENERIC:'createOrUpdateAGenericResponse.json',
            SECTION_ROOM:"createOrUpdateSectionRoom.json",
            ROOM_ITEM:"createOrUpdateRoomItem.json",
            SECTION:"createOrUpdateSection.json",
        },
        POST:1
    },

    MANAGEDATA_DROPDOWNS:{
        END_POINT:"getGenericDropdownValue.json",
        POST:1
    },
    MODULE_DATA:{
        END_POINT:"detailModuleData.json",
        MODULES:{
            NEIGHBORHOOD:"neighborhood",
            BUILDER:"builder",
            TAG:"tag",
            DISCLOSURE:"disclosure",
            GENERIC:'generic',
            SECTION_ROOM:"sectionRoom",
            ROOM_ITEM:"roomItem",
            SECTION:"section",
            USER:"user",
        },
        POST:1
    },

    SETTINGS_CLIENTS:{
        END_POINTS:{
           GET_CLIENT_SETTINGS: "getClientSetting.json",
           UPDATE_CLIENT_SETTINGS:"updateClientSetting.json",
           ADD_USER:"createUser.json",
           UPDATE_USER:"updateUser.json",
           SEND_REMINDER:"sendEmailReminder.json",
           SEND_INVITE:"sendInvitationEmail.json",
        },
        POST:1
    },

    SEND_REMINDER_ALL:{
        END_POINT:"sendEmailReminderAll.json",
        POST:1
    },
    IMPORT_CSV:{
        END_POINT:"importModules.json",
        POST:1
    }
}